### ISSUE TITLE
There is no prompt word module

### ISSUE THREAD

**Issue by jimmeguy1967** [IamCreateAI/Ruyi-Models#7] opened 2024-12-19 00:39 UTC
There is no prompt word module？why？This is puzzling！

**Comment by cellzero** [comment] 2024-12-19 01:53
Thank you for using the Ruyi model.

The text-to-video feature is currently under review for legal risks and will only be made available once appropriate safety measures are implemented.

However, we cannot guarantee when it will be released or if it will be made available at all.

**Comment by cellzero** [comment] 2024-12-19 01:56
Duplicate of #3.

**Closed** 2024-12-19 11:36 UTC
Labels: duplicate
